/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("maven-publish") // 发布插件
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    mainClass = "org.example.app.App"
}


dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.18.2")
    implementation(project(":utilities"))
    implementation(libs.apacheHttpClient)
}

tasks.register<Exec>("MyExecTask") {
    commandLine("java", "-version")
}


publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "com.example.ykgmy"
            artifactId = "gradle-study"
            version = "1.0"
            from(components["java"])
        }
    }
}